<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />


    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>

            <!-- <material name="blue" /> -->
        </visual>

        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>

        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}"
            h="${camera_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="camera_optical_link" />

    <joint name="camera_optical_link" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link" />
        <child link="camera_optical_link" />
    </joint>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${base_length/2.0} 0 ${base_height/2.0}" rpy="0 0 0" />
    </joint>


    <gazebo reference="camera_link">
        <sensor type="camera" name="camera1">
          <update_rate>30.0</update_rate>
          <visualize>true</visualize>
          <pose>0 0 0 0 0 0</pose>
          <!-- <camera name="head">
            <horizontal_fov>1.3962634</horizontal_fov>
            <image>
              <width>1920</width>
              <height>1080</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>100</far>
            </clip>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.007</stddev>
            </noise>
            
          </camera> -->
          <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <frameName>camera_optical_link</frameName>
            <!-- <alwaysOn>true</alwaysOn>
            <updateRate>0.0</updateRate>
            <cameraName>rrbot/camera1</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2> -->
          </plugin>
        </sensor>
      </gazebo>

</robot>