<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Material Definitions -->
    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="leftwheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="rightwheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    
    <gazebo reference="castorwheel_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">

            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>
      
            <!-- wheels -->
            <left_joint>base_leftwheel_joint</left_joint>
            <right_joint>base_rightwheel_joint</right_joint>
      
            <!-- kinematics -->
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      
            <!-- input -->
            <command_topic>cmd_vel</command_topic>
      
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
      
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
      
          </plugin>
    </gazebo>

</robot>
